service:
  name: node-js-serverless-lambda-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: sa-east-1
  environment:
    AUCTIONS_TABLE_NAME: AuctionsTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/AuctionsTable
  
resources:
  Resources:
    AuctionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AuctionsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
functions:
  CreateAuctionHandler:
    handler: src/handlers/CreateAuctionHandler.handler
    events:
      - http:
          method: POST
          path: /auction
  GetAllAuctionsHandler:
    handler: src/handlers/GetAllAuctionsHandler.handler
    events:
      - http:
          method: GET
          path: /auction
  GetAuctionsHandler:
    handler: src/handlers/GetAuctionHandler.handler
    events:
      - http:
          path: /auction/{id}
          method: GET
          request:
            parameters:
              paths:
                id: true
          
custom:
  bundle:
    linting: false